/**
 * Lane B caption ingest: render clipCaptions.ts -> the engine's openerCaptions.ts.
 *
 * The render session ships per-word caption data for the 37 onboarding clips as
 * src/components/flow-designer/clipCaptions.ts (keyed by clip name, no extension).
 * The engine's karaoke reads src/onboarding-flow/renderer/openerCaptions.ts,
 * keyed by the clip SRC PATH used in the beat's meta.mp3Assets file field.
 * This script maps name -> /voice/ob/<name>.wav and regenerates the engine file
 * (data only; the lookup function is emitted verbatim).
 *
 * The greeting is NOT ingested here: it plays through the component-owned
 * SplashIntro with its own splashCaptions.ts.
 *
 * Word-count note: six long clips carry whisper's raw tokenization (split
 * "check-in" / "100%"), so caption word counts can differ by one from the
 * display text. That is safe by design: onsetsForDisplayWords maps token onsets
 * onto display words proportionally, and the caption word TEXT is never shown.
 *
 * Run:
 *   npx tsx scripts/flow-sync/ingest-captions.ts \
 *     --clip-captions <clipCaptions.ts> --clips-manifest <manifest.txt> \
 *     --render-sha <sha> --out <openerCaptions.ts>
 *
 * NO EM DASHES.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

function arg(name: string): string {
  const i = process.argv.indexOf('--' + name);
  if (i < 0 || !process.argv[i + 1]) throw new Error('missing --' + name);
  return process.argv[i + 1];
}

interface CaptionWord {
  t: number;
  w: string;
}
interface CaptionLine {
  start: number;
  end: number;
  words: CaptionWord[];
}

function loadClipCaptions(path: string): Record<string, CaptionLine[]> {
  const src = readFileSync(path, 'utf8');
  const anchor = src.indexOf('CLIP_CAPTIONS: Record<string, CaptionLine[]> =');
  if (anchor < 0) throw new Error('CLIP_CAPTIONS literal not found in ' + path);
  const open = src.indexOf('{', anchor);
  const end = src.indexOf('\n};', open);
  if (open < 0 || end < 0) throw new Error('CLIP_CAPTIONS bounds not found');
  const literal = src.slice(open, end + 2);
  return new Function('"use strict"; return ' + literal)() as Record<string, CaptionLine[]>;
}

function main(): void {
  const renderSha = arg('render-sha');
  const outPath = resolve(arg('out'));
  const captions = loadClipCaptions(arg('clip-captions'));
  const manifest = readFileSync(arg('clips-manifest'), 'utf8')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((p) => '/' + p.replace(/^public\//, ''));
  const wavs = manifest.filter((f) => f.startsWith('/voice/ob/'));

  const problems: string[] = [];
  const names = Object.keys(captions).sort();
  for (const name of names) {
    if (!wavs.includes('/voice/ob/' + name + '.wav')) {
      problems.push('caption entry has no clip file: ' + name);
    }
    for (const line of captions[name]) {
      if (!line.words.length) problems.push('empty caption line in ' + name);
      for (const w of line.words) {
        if (typeof w.t !== 'number' || typeof w.w !== 'string') {
          problems.push('malformed word in ' + name);
          break;
        }
      }
    }
  }
  for (const f of wavs) {
    const name = f
      .split('/')
      .pop()!
      .replace(/\.wav$/, '');
    if (!captions[name]) problems.push('clip file has no caption entry: ' + name);
  }
  if (problems.length) {
    for (const p of problems) console.error('  - ' + p);
    throw new Error('caption ingest failed with ' + problems.length + ' problem(s)');
  }

  // Splice the entries into the engine's existing openerCaptions.ts, clip-NAME
  // keyed (the dual-key lookup on main accepts the render's format unchanged).
  // Everything outside the OPENER_CAPTIONS literal is preserved verbatim, so
  // header and lookup-code changes on main never fight this generator.
  const target = readFileSync(arg('target'), 'utf8');
  const anchor = target.indexOf('const OPENER_CAPTIONS: Record<string, CaptionLine[]> = {');
  if (anchor < 0) throw new Error('OPENER_CAPTIONS literal not found in the target file');
  const open = target.indexOf('{', anchor);
  const close = target.indexOf('\n};', open);
  if (close < 0) throw new Error('OPENER_CAPTIONS literal end not found');
  const entries = names
    .map((name) => "  '" + name + "': " + JSON.stringify(captions[name]) + ',')
    .join('\n');
  const body =
    '{\n' +
    '  // GENERATED by scripts/flow-sync/ingest-captions.ts from the render branch\n' +
    '  // clipCaptions.ts at ' +
    renderSha +
    ' (mlx-whisper word timestamps). Re-run the\n' +
    '  // ingest when a clip is re-recorded; do not hand-edit the entries. The greeting\n' +
    '  // stays in splashCaptions.ts (component-owned SplashIntro).\n' +
    entries +
    '\n}';
  const out = target.slice(0, open) + body + target.slice(close + 2);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, out, 'utf8');
  console.log('[captions] wrote ' + outPath + ' (' + names.length + ' clips, name-keyed)');
}

main();
