#!/usr/bin/env python3
"""Supabase -> repo file sync for onboarding beat contexts.

Reads `beat_contexts` and `onboarding_globals` from Supabase and writes
  api/_lib/llm/onboarding/beatContexts.generated.json
which beatContexts.ts merges at runtime to override hand-authored defaults.

`allowedTools` is NOT included in the generated file -- it is code-owned in
beatContexts.ts and never stored in Supabase.

Idempotent: only writes the file when content has actually changed (compares
the new JSON against whatever is on disk). Safe to run repeatedly on a
schedule or on-demand.

Usage:
    python scripts/voice-sync/sync_beat_contexts.py
    python scripts/voice-sync/sync_beat_contexts.py --dry-run
    python scripts/voice-sync/sync_beat_contexts.py --screen-id ONBOARD-BEGINNER-03

Env (loaded from project-root .env / .env.local in dev; from GH secrets in CI):
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
load_dotenv(PROJECT_ROOT / ".env")
load_dotenv(PROJECT_ROOT / ".env.local")
load_dotenv(Path(__file__).resolve().parent / ".env")

from lib.supabase_client import get_client

BEAT_TABLE = "beat_contexts"
GLOBALS_TABLE = "onboarding_globals"

OUTPUT_PATH = (
    PROJECT_ROOT / "api" / "_lib" / "llm" / "onboarding" / "beatContexts.generated.json"
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--dry-run", action="store_true",
                   help="fetch from Supabase, log diff, do not write file")
    p.add_argument("--screen-id", metavar="ID",
                   help="fetch only this screen_id (for debugging; full file not written)")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        print("ERROR: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set", file=sys.stderr)
        return 1

    sb = get_client()

    # Fetch globals row.
    gres = sb.table(GLOBALS_TABLE).select("*").eq("id", "default").execute()
    if not gres.data:
        print("ERROR: no row in onboarding_globals with id='default'. Run seed_beat_contexts.py first.",
              file=sys.stderr)
        return 2

    global_row = gres.data[0]
    bundle_version: int = global_row.get("bundle_version", 1)
    global_context: str = global_row["global_context"]

    # Fetch beat rows.
    query = sb.table(BEAT_TABLE).select("screen_id, context, opener, version, content_hash")
    if args.screen_id:
        query = query.eq("screen_id", args.screen_id)
    bres = query.order("screen_id").execute()

    beats: dict[str, dict] = {}
    for row in (bres.data or []):
        screen_id = row["screen_id"]
        beats[screen_id] = {
            "context":     row["context"],
            "opener":      row.get("opener"),      # null -> None -> omitted below if null
            "version":     row["version"],
            "contentHash": row.get("content_hash"),
        }
        # Drop None opener to keep the JSON clean (beatContexts.ts checks for undefined).
        if beats[screen_id]["opener"] is None:
            del beats[screen_id]["opener"]

    print(f"Fetched {len(beats)} beats from Supabase (bundle_version={bundle_version})")

    if args.screen_id:
        if args.screen_id in beats:
            print(json.dumps(beats[args.screen_id], indent=2))
        else:
            print(f"  screen_id {args.screen_id!r} not found in beat_contexts", file=sys.stderr)
        return 0

    # Build output document.
    output = {
        "_comment":      "Auto-generated by scripts/voice-sync/sync_beat_contexts.py. Do not edit manually.",
        "_generatedAt":  datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "bundleVersion": bundle_version,
        "global":        global_context,
        "beats":         beats,
    }

    new_json = json.dumps(output, indent=2, ensure_ascii=False) + "\n"

    # Compare against what is on disk (idempotency check).
    existing_json: str | None = None
    if OUTPUT_PATH.exists():
        try:
            existing_json = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError:
            pass

    # Strip the _generatedAt timestamp for comparison so a re-run with no DB
    # changes does not count as a change.
    def _strip_timestamp(j: str) -> str:
        import re
        return re.sub(r'"_generatedAt":\s*"[^"]*"', '"_generatedAt": ""', j)

    if existing_json is not None and _strip_timestamp(existing_json) == _strip_timestamp(new_json):
        print(f"  no changes detected -- {OUTPUT_PATH.relative_to(PROJECT_ROOT)} is up to date")
        return 0

    # Log what changed vs what is on disk.
    if existing_json is not None:
        try:
            old = json.loads(existing_json)
            old_beats: dict = old.get("beats", {})
            new_beats: dict = output["beats"]
            all_ids = sorted(set(old_beats) | set(new_beats))
            changed = [sid for sid in all_ids if old_beats.get(sid) != new_beats.get(sid)]
            added   = [sid for sid in all_ids if sid not in old_beats]
            removed = [sid for sid in all_ids if sid not in new_beats]
            for sid in added:
                print(f"  + {sid} (new)")
            for sid in removed:
                print(f"  - {sid} (removed)")
            for sid in changed:
                if sid not in added and sid not in removed:
                    print(f"  ~ {sid} (updated)")
            if old.get("global") != output["global"]:
                print("  ~ global_context (updated)")
            if old.get("bundleVersion") != bundle_version:
                print(f"  ~ bundleVersion {old.get('bundleVersion')} -> {bundle_version}")
        except Exception:
            print("  (could not diff against existing file)")
    else:
        print(f"  (no existing file -- writing fresh)")

    if args.dry_run:
        print(f"\n[dry-run] would write {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(new_json, encoding="utf-8")
    print(f"\nWrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)} ({len(new_json)} bytes, {len(beats)} beats)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
