import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { contractPath, contextOutputs, repositoryRoot } from './config';
import { readContract, type OnboardingContract } from './lib/readContract';
import { compareKeys, stableJson } from './lib/serialize';

type Metadata = { contractRevision: string; contractSha256: string };

type BackendBeat = {
  context?: string | null;
  opener?: string | null;
  expectedResponse?: unknown;
  type?: string;
  script?: unknown[];
  elements?: unknown[];
  beatIO?: unknown;
  conversation?: unknown;
  voice?: unknown;
};

type FrontendBeat = BackendBeat & {
  allowedTools: string[];
  step: number | null;
  targetStep: number | null;
};

export function projectContextArtifacts(contract: OnboardingContract, metadata: Metadata) {
  const beatsById = new Map(contract.beats.map((beat) => [beat.id, beat]));
  if (beatsById.size !== contract.beats.length) throw new Error('Contract contains duplicate beat IDs.');

  const resolving = new Set<string>();
  const resolvedContexts = new Map<string, string | null | undefined>();
  const resolveContext = (beatId: string): string | null | undefined => {
    const existing = resolvedContexts.get(beatId);
    if (existing !== undefined || resolvedContexts.has(beatId)) return existing;
    const beat = beatsById.get(beatId);
    if (!beat) throw new Error(`Context inheritance source does not exist: ${beatId}`);
    if (resolving.has(beatId)) throw new Error(`Context inheritance cycle includes: ${beatId}`);
    resolving.add(beatId);
    const inherited = beat.inheritsContextFrom ? resolveContext(beat.inheritsContextFrom) : undefined;
    const value = beat.context === undefined ? inherited : beat.context;
    resolving.delete(beatId);
    resolvedContexts.set(beatId, value);
    return value;
  };

  const backendBeats: Record<string, BackendBeat> = {};
  const frontendBeats: Record<string, FrontendBeat> = {};
  for (const beat of [...contract.beats].sort((left, right) => left.order - right.order)) {
    const context = resolveContext(beat.id);
    const opener = beat.openerSeq == null ? undefined : beat.script?.find((line) => line.seq === beat.openerSeq)?.words;
    if (beat.openerSeq != null && opener === undefined) {
      throw new Error(`Beat ${beat.id} openerSeq does not reference a script line.`);
    }
    const common: BackendBeat = {
      ...(context === undefined ? {} : { context }),
      ...(opener === undefined ? {} : { opener }),
      ...(beat.expectedResponse === undefined ? {} : { expectedResponse: beat.expectedResponse }),
      type: beat.type,
      script: beat.script ?? [],
      elements: beat.elements ?? [],
      beatIO: beat.beatIO ?? null,
      conversation: beat.conversation ?? null,
      voice: beat.voice ?? null,
    };
    backendBeats[beat.id] = common;
    frontendBeats[beat.id] = {
      ...common,
      allowedTools: (beat.allowedTools ?? []).map((tool) =>
        typeof tool === 'string' ? tool : tool.name,
      ),
      step: null,
      targetStep: null,
    };
  }

  return {
    backend: {
      _comment: 'AUTO-GENERATED by scripts/onboarding/generate.ts from onboarding-contract.v1.json. Do not edit.',
      bundleVersion: 1,
      global: contract.globalContext,
      beats: backendBeats,
    },
    frontend: {
      _comment: 'AUTO-GENERATED by scripts/onboarding/generate.ts from onboarding-contract.v1.json. Do not edit.',
      bundleVersion: 1,
      allTools: [...new Set(Object.values(frontendBeats).flatMap((beat) => beat.allowedTools))].sort(compareKeys),
      global: contract.globalContext,
      beats: frontendBeats,
    },
  };
}

export function generateContextArtifacts(inputPath = contractPath): void {
  const { contract, contractSha256 } = readContract(inputPath);
  const metadata = { contractRevision: contract.contractRevision, contractSha256 };
  const artifacts = projectContextArtifacts(contract, metadata);
  writeOutput(contextOutputs.backend, stableJson(artifacts.backend));
  writeOutput(contextOutputs.backendMeta, stableJson(metadata));
  writeOutput(contextOutputs.frontend, stableJson(artifacts.frontend));
  writeOutput(contextOutputs.frontendMeta, stableJson(metadata));
}

function writeOutput(relativePath: string, content: string): void {
  const outputPath = resolve(repositoryRoot, relativePath);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, 'utf8');
}

if (import.meta.url === `file://${process.argv[1]}`) generateContextArtifacts();
