/**
 * Generate src/generated/beat_contexts.json — the FRONTEND-bundled onboarding
 * beat context that feeds Vapi (and any frontend consumer) the SAME content
 * Direct-LLM uses, plus the navigation machinery it needs.
 *
 * Three sources, one bundle:
 *   - coach copy + opener  ← beatContexts.ts (Supabase-synced)
 *   - allowedTools         ← beatContexts.ts (code-owned)
 *   - step + target_step   ← the FLOW BUILDER (onboarding-beginner-v1.generated.json),
 *                            the canonical order. step = persist.step ?? the engine's
 *                            persist-null override; target_step follows nextId and SKIPS
 *                            same-step nodes (so habit-select/habit-schedule, both step 5,
 *                            advance to plan-review at step 6 — "habits are one step").
 *
 *   npx tsx scripts/build-beat-bundle.ts
 */
import { writeFileSync } from 'fs';
import { resolve } from 'path';
import {
  BEAT_CONTEXTS,
  GLOBAL_ONBOARDING_CONTEXT,
  BEAT_CONTEXT_VERSION,
} from '../api/_lib/llm/onboarding/beatContexts.ts';
import flow from '../src/onboarding-flow/flows/onboarding-beginner-v1.generated.json';

// Mirror of ENGINE_PERSISTLESS_STEP in useFlowOrchestrator.ts — persist-null
// beats whose canonical advance threshold is engine-local (NOT the legacy
// SCREEN_TO_STEP). Keep in sync with the orchestrator.
const ENGINE_PERSISTLESS_STEP: Record<string, number> = {
  'ONBOARD-BEGINNER-06': 6,
};

interface FlowNode {
  id: string;
  screenId: string;
  nextId?: string | null;
  persist?: { step: number };
}
const nodes = flow.nodes as FlowNode[];
const byId: Record<string, FlowNode> = {};
const byScreen: Record<string, FlowNode> = {};
for (const n of nodes) {
  byId[n.id] = n;
  byScreen[n.screenId] = n;
}

function beatStep(n: FlowNode | undefined): number | undefined {
  if (!n) return undefined;
  return n.persist?.step ?? ENGINE_PERSISTLESS_STEP[n.screenId];
}

// The step Vapi's navigate_next must reach to advance PAST this beat: follow
// nextId, skipping nodes that share this beat's step (same step = same engine
// beat), and return the first DIFFERENT step. Fork (no nextId) → the smallest
// flow step greater than this one. Terminal chain → this step + 1.
function targetStep(n: FlowNode): number | undefined {
  const here = beatStep(n);
  if (here == null) return undefined; // terminal (into-app) — no navigate_next
  let cur: FlowNode | undefined = n.nextId ? byId[n.nextId] : undefined;
  const guard = new Set<string>();
  while (cur && !guard.has(cur.id)) {
    guard.add(cur.id);
    const s = beatStep(cur);
    if (s != null && s !== here) return s;
    cur = cur.nextId ? byId[cur.nextId] : undefined;
  }
  if (!n.nextId) {
    // Fork: smallest flow step strictly greater than here.
    const greater = nodes.map(beatStep).filter((s): s is number => s != null && s > here);
    return greater.length ? Math.min(...greater) : here + 1;
  }
  return here + 1; // chain ended at a terminal/persist-null node
}

const beats: Record<
  string,
  {
    context: string;
    opener?: string;
    allowedTools: string[];
    step: number | null;
    targetStep: number | null;
  }
> = {};
const toolUniverse = new Set<string>();

for (const [screenId, beat] of Object.entries(BEAT_CONTEXTS)) {
  const allowedTools = [...beat.allowedTools];
  allowedTools.forEach((t) => toolUniverse.add(t));
  const node = byScreen[screenId];
  beats[screenId] = {
    context: beat.context,
    ...(beat.opener !== undefined ? { opener: beat.opener } : {}),
    allowedTools,
    step: node ? (beatStep(node) ?? null) : null,
    targetStep: node ? (targetStep(node) ?? null) : null,
  };
}

const out = {
  _comment:
    'AUTO-GENERATED by scripts/build-beat-bundle.ts from beatContexts.ts (synced copy + allowedTools) + the flow builder (step + target_step). Do not edit. Re-run after sync_beat_contexts.py or a flow change.',
  bundleVersion: BEAT_CONTEXT_VERSION,
  allTools: [...toolUniverse].sort(),
  global: GLOBAL_ONBOARDING_CONTEXT,
  beats,
};

const path = resolve(import.meta.dirname, '../src/generated/beat_contexts.json');
writeFileSync(path, JSON.stringify(out, null, 2) + '\n', 'utf-8');
const withNav = Object.values(beats).filter((b) => b.targetStep != null).length;
console.log(
  `Wrote src/generated/beat_contexts.json (${Object.keys(beats).length} beats, ${withNav} with nav target, global ${GLOBAL_ONBOARDING_CONTEXT.length} chars)`,
);
