/**
 * Generate src/generated/beat_contexts.json — the FRONTEND-bundled onboarding
 * beat context. Source of truth is the backend beatContexts.ts (synced coach
 * copy + opener from Supabase, code-owned allowedTools) enriched with the engine
 * step model (onboardingStepBeats.ts). The frontend can't import the backend
 * module, so this bundle is how Vapi's getScreenContext reads the same content
 * Direct-LLM uses. Run after sync_beat_contexts.py (and in the build).
 *
 *   npx tsx scripts/build-beat-bundle.ts
 */
import { writeFileSync } from 'fs';
import { resolve } from 'path';
import {
  BEAT_CONTEXTS,
  GLOBAL_ONBOARDING_CONTEXT,
  BEAT_CONTEXT_VERSION,
} from '../api/_lib/llm/onboarding/beatContexts.ts';
import { stepForScreenId } from '../src/lib/onboarding/onboardingStepBeats.ts';

const beats: Record<
  string,
  { context: string; opener?: string; allowedTools: string[]; step: number | null }
> = {};

const toolUniverse = new Set<string>();

for (const [screenId, beat] of Object.entries(BEAT_CONTEXTS)) {
  const allowedTools = [...beat.allowedTools];
  allowedTools.forEach((t) => toolUniverse.add(t));
  beats[screenId] = {
    context: beat.context,
    ...(beat.opener !== undefined ? { opener: beat.opener } : {}),
    allowedTools,
    step: stepForScreenId(screenId) ?? null,
  };
}

const out = {
  _comment:
    'AUTO-GENERATED by scripts/build-beat-bundle.ts from beatContexts.ts + onboardingStepBeats.ts. Do not edit. Re-run after sync_beat_contexts.py.',
  bundleVersion: BEAT_CONTEXT_VERSION,
  // Full onboarding tool universe (union of every beat's allowedTools) so the
  // frontend composer can derive the FORBIDDEN list without hardcoding it.
  allTools: [...toolUniverse].sort(),
  global: GLOBAL_ONBOARDING_CONTEXT,
  beats,
};

const path = resolve(import.meta.dirname, '../src/generated/beat_contexts.json');
writeFileSync(path, JSON.stringify(out, null, 2) + '\n', 'utf-8');
console.log(
  `Wrote src/generated/beat_contexts.json (${Object.keys(beats).length} beats, ${out.allTools.length} tools, global ${GLOBAL_ONBOARDING_CONTEXT.length} chars)`,
);
